# Generated by Django 4.1 on 2022-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('White & Cream', 'White & Cream'), ('Pink', 'Pink'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Apricot & Orange', 'Apricot & Orange')], max_length=200, null=True),
        ),
    ]
